[tool.poetry]
name = "cloudconnectlib"
version = "2.0.3"
description = "APP Cloud Connect"
authors = ["Addon Factory template <addonfactory@splunk.com>"]
license = "APACHE-2.0"

[tool.poetry.dependencies]
python = "^3.7"
jsonschema = "2.6.0"
jinja2 = "2.10.1"
jsonpath-rw = "1.4.0"
httplib2 = "0.14.0"
splunk-sdk = "1.6.6"
sortedcontainers = "2.1.0"
munch = "2.3.2"
splunktaucclib = "^4.2.0"
solnlib = "^3.0.5"
six = "future"
future = "^0.18.2"
configparser = "^5.0.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-cov = "^2.11.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
